### PR TITLE
Modify get_data

### PR DESCRIPTION
**Pull request by JuanVallarta**
Added the option to choose the "report" branch, and to get the raw version when non "-" is found in the name of the branch

### CODE REVIEW

**Comment by benubah** [comment]
@JuanVallarta Thanks! What do you hope to achieve with the `grepl()`?

**Comment by JuanVallarta** [comment]
> @JuanVallarta Thanks! What do you hope to achieve with the `grepl()`?

Basically to account for all the branch names that do not contain a  "-" in their names, (e.g. "report"). (it could also be: version == "main" | version=="report", but trying to think in future scenarios where someone do not include a "-" in the name of the branch)

This is because we are testing a branch ("report") in the test directory data where the column formats are different from the current ones, and we need to access the data from this specific branch.

**Comment by benubah** [comment]
thanks! I tried a test case like `data_testdir <- shinyfind::get_data("testdir", "covid19", version = "report")` and it looks good

**Comment by JuanVallarta** [comment]
> thanks! I tried a test case like `data_testdir <- shinyfind::get_data("testdir", "covid19", version = "report")` and it looks good

Thanks!

**Pull request merged**
