### PR TITLE
robust_aggregation

### PR DESCRIPTION
**Pull request by christophsax**
This makes discontiued avoids computing period means and sums for discontinued series.

@benubah can you review and make sure this works with latest tracker. Once it is merged, it will automatically be picked up by the workflow. 

Afterwards, can you make sure the numbers are the same in the workflow and in the tracker (i.e., we have the same missing values).

### CODE REVIEW

**Comment by benubah** [comment]
@christophsax I added changes for group summaries using the new `robust_` fnc. Does this look like what we expect?

**Comment by christophsax** [comment]
@benubah can you review? 

- Do the results make sense in the tracker app? Do we get meaningfull per-capita measures for groups?
- Can you verify that no value is reported if over-time averages if data is missing for a long time? E.g., for turkey?

**Comment by benubah** [comment]
@christophsax The `avg_cap_` variables are the same with `sum_cap_`  variables. Is this the intention? A reprex is shown below:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
remotes::install_github("dsbbfinddx/shinyfind", ref="smart-aggregations")
#> Skipping install of 'shinyfind' from a github remote, the SHA1 (c19bcc30) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(shinyfind)

heartbeat_local <- NA
. <- shinyfind::get_data_all()
data_all <- .$data_all
country_last_update_info <- .$country_last_update_info


summarized_who_regions <- 
  data_all |>
  filter(set == "country") |>
  select(-name, -set) |>
  left_join(country_last_update_info, by = "unit") |>
  filter(!is.na(last_update)) |>
  filter(time == as.Date("2022-04-06")) |>
  shinyfind::summarize_over_time() |>
  shinyfind::summarize_over_group("who_region") |>
  select(-starts_with('pop')) |>
  relocate(starts_with('cap_'), .before = starts_with('avg_')) 



print(summarized_who_regions |>
        select(avg_cap_new_cases, 
               sum_cap_new_cases,
               avg_cap_new_tests,
               sum_cap_new_tests)
      )
#> # A tibble: 6 x 4
#>   avg_cap_new_cases sum_cap_new_cases avg_cap_new_tests sum_cap_new_tests
#>               <dbl>             <dbl>             <dbl>             <dbl>
#> 1           0.00246           0.00246            0.0879            0.0879
#> 2           0.0704            0.0704             1.49              1.49  
#> 3           0.00892           0.00892            0.795             0.795 
#> 4           0.734             0.734              4.51              4.51  
#> 5           0.0154            0.0154             0.349             0.349 
#> 6           0.243             0.243              0.960             0.960
```

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by benubah** [comment]
@christophsax  And we would also need https://github.com/dsbbfinddx/FINDCov19Tracker/pull/27 to get everything to work as expected

**Comment by benubah** [comment]
We can merge now

**Pull request merged**
